### ISSUE TITLE
Can I get followers list with this library?

### ISSUE THREAD

**Issue by cellojaan** [mgarciaguerrero/Instagram-Android-API#1]
Hi.

Can I get followers and following list with this library?
If yes, any example code?
Thanks.

**Comment by mgarciaguerrero** [comment]
Hi @cellojaan,
Yes, it is implemented (see [RelationshipAdapter](https://github.com/mgarciaguerrero/instagram-android-api/blob/master/library/src/main/java/com/marcg/instagram/android/endpoints/adapter/RelationshipAdapter.java)). However, I've seen that Instagram API Platform has deprecated those endpoints. Check the changelog for more information:

- https://www.instagram.com/developer/changelog/

**Comment by cellojaan** [comment]
@mgarciaguerrero 
Can you make an example please? I really want to use this library.
Thanks.
